import { CONFIG, STATE } from "./config.js";

function calculateDistanceKm(lat1, lon1, lat2, lon2) {
  const R = 6371; // Earth's radius in kilometers

  const degToRad = (deg) => deg * (Math.PI / 180);

  const dLat = degToRad(lat2 - lat1);
  const dLon = degToRad(lon2 - lon1);

  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos(degToRad(lat1)) *
      Math.cos(degToRad(lat2)) *
      Math.sin(dLon / 2) *
      Math.sin(dLon / 2);

  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  const distance = R * c; // Distance in km

  return distance;
}

/**
 * Generates alerts by checking if any flights or airports are within the defined
 * alert radius of any disaster event (Earthquakes or NASA EONET events).
 * Stores the generated alerts in STATE.alerts.
 */
function generateAlerts() {
  // Clear previous alerts
  STATE.alerts = [];

  const disasterSources = [...STATE.earthquakes, ...STATE.events];
  const flights = STATE.flights;
  const alertRadiusKm = parseFloat(STATE.filters.alertRadius);

  if (isNaN(alertRadiusKm) || alertRadiusKm <= 0) {
    console.warn("Invalid alert radius, skipping alert generation.");
    return;
  }

  flights.forEach((flight) => {
    // Skip flights that are explicitly on the ground
    if (flight.onGround) return;

    disasterSources.forEach((disaster) => {
      const distance = calculateDistanceKm(
        flight.latitude,
        flight.longitude,
        disaster.latitude,
        disaster.longitude
      );

      if (distance <= alertRadiusKm) {
        // Determine severity based on disaster type and distance
        let severity = CONFIG.COLORS.MEDIUM_RISK;
        let description = `Flight ${flight.callsign} is ${distance.toFixed(
          1
        )} km away from ${disaster.title || disaster.place}.`;

        if (flight.emergency) {
          severity = CONFIG.COLORS.HIGH_RISK;
          description = `🚨 EMERGENCY FLIGHT ${
            flight.callsign
          } is in proximity (${distance.toFixed(1)} km) to ${
            disaster.title || disaster.place
          }.`;
        } else if (
          disaster.type === "earthquake" &&
          disaster.magnitude >= 7.0
        ) {
          severity = CONFIG.COLORS.HIGH_RISK;
        } else if (
          disaster.type === "event" &&
          disaster.category.includes("Wildfire")
        ) {
          // Wildfires often pose immediate airspace danger
          severity = CONFIG.COLORS.MEDIUM_RISK;
        } else if (distance < alertRadiusKm / 2) {
          severity = CONFIG.COLORS.MEDIUM_RISK; // Closer proximity elevates risk
        } else {
          severity = CONFIG.COLORS.LOW_RISK;
        }

        STATE.alerts.push({
          id: `${flight.icao24}-${disaster.id}`,
          type: "FLIGHT_PROXIMITY",
          severity: severity,
          message: description,
          flight: flight,
          disaster: disaster,
          distance: distance,
        });
      }
    });
  });

  // --- 2. Check Disaster Severity (e.g., Tsunami) ---
  // If a high-impact disaster exists (e.g., Tsunami warning), create an alert even if no flight is near.
  disasterSources.forEach((disaster) => {
    if (disaster.tsunami) {
      STATE.alerts.push({
        id: `TSUNAMI-${disaster.id}`,
        type: "TSUNAMI_WARNING",
        severity: CONFIG.COLORS.HIGH_RISK,
        message: `🌊 Tsunami Alert: Confirmed or potential tsunami generated by M${disaster.magnitude.toFixed(
          1
        )} event near ${disaster.place}.`,
        disaster: disaster,
        distance: 0,
      });
    }
    // Could add logic here for other high-severity events like Red-level event alerts
  });

  // Remove duplicates (though the unique ID above should handle most cases) and sort by severity (High first)
  STATE.alerts.sort((a, b) => {
    const severityOrder = [
      CONFIG.COLORS.HIGH_RISK,
      CONFIG.COLORS.MEDIUM_RISK,
      CONFIG.COLORS.LOW_RISK,
    ];
    return (
      severityOrder.indexOf(b.severity) - severityOrder.indexOf(a.severity)
    );
  });
}

export { generateAlerts, calculateDistanceKm };
